// <auto-generated />
using System;
using AvatarNET.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvatarNET.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Avatar.Shared.Models.AvatarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AvatarModel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae4f603d-2015-46c4-bbc4-73ba5cea7783"),
                            Name = "Ethan"
                        },
                        new
                        {
                            Id = new Guid("df248a4f-9ab9-45c5-876a-1e5adf70643b"),
                            Name = "Jason"
                        },
                        new
                        {
                            Id = new Guid("09aac140-5066-4a8d-aacf-a3203a88562a"),
                            Name = "Will"
                        },
                        new
                        {
                            Id = new Guid("18b5cb25-9e98-409e-a4fe-59667c9ed3c3"),
                            Name = "Alisha"
                        },
                        new
                        {
                            Id = new Guid("638d2c38-25e8-43d6-8435-77b7c0537b81"),
                            Name = "Maia"
                        },
                        new
                        {
                            Id = new Guid("01a74d8b-28c9-465a-8e0e-76e6ebeb3a4e"),
                            Name = "Paige"
                        });
                });

            modelBuilder.Entity("Avatar.Shared.Models.Background", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Background");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ecff033-aa87-4ad7-adbd-1a3733907068"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("cd57fb2f-2840-4d19-9661-d5947cee6c4d"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("a84d4767-2521-462f-b47b-e2eb15865fd9"),
                            Color = "Red"
                        });
                });

            modelBuilder.Entity("Avatar.Shared.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plan");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b631f86-4e90-4fdb-bd3f-ea8b775b913e"),
                            Type = "Basic"
                        });
                });

            modelBuilder.Entity("Avatar.Shared.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalesTax")
                        .HasColumnType("money");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("money");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDue")
                        .HasColumnType("money");

                    b.Property<Guid>("VoiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Avatar.Shared.Models.Voice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Voice");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffd7fa43-9848-4763-8b4b-f5c8db796e7a"),
                            Language = "Polish"
                        },
                        new
                        {
                            Id = new Guid("73ed61f0-fcb2-4b54-b0bc-82ed294bb7bd"),
                            Language = "English"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
